version: "2"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/src/app
    expose:
      - "10000"
    ports:
      - "10000:10000"
    command: "npm start"